# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Jerry Xu
tagline:          'Statistics & Computer Science'
description:      'University student studying math, stats and cs. People say I have to narrow my focus. I say that is no fun.' 
url:              http://jerry-ye-xu.github.io/
baseurl:          /

author:        
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
repo:             https://github.com/jerry-ye-xu/jerry-ye-xu.github.io
