# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
plugins:          [jekyll-paginate, jekyll-gist]

# Setup
title:            Jerry Xu
tagline:          'Statistics & Computer Science'
description:      'University student studying math, stats and cs. People say I have to narrow my focus. I say that is no fun.' 
url:              http://jerry-ye-xu.github.io/
baseurl:          /

author:        
  name:           'Jerry Xu'
  url:            http://jerry-ye-xu.github.io/

paginate:         5

# Custom vars
version:          1.0.0

github:           https://github.com/jerry-ye-xu/
repo:             https://github.com/jerry-ye-xu/jerry-ye-xu.github.io
