# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
plugins:          
  - jekyll-paginate
  - jekyll-gist
  - jekyll-toc

# Setup
title:            Jerry Xu
tagline:          'Statistics & Computer Science'
description:      'Exploring multiple rabbit holes'
subdescription:   'math | stats | comp sci' 
url:              http://jerry-ye-xu.github.io/
baseurl:          /

author:        
  name:           'Jerry Xu'
  url:            http://jerry-ye-xu.github.io/

paginate:         5

# Custom vars
version:          1.0.1

github:           https://github.com/jerry-ye-xu/
repo:             https://github.com/jerry-ye-xu/jerry-ye-xu.github.io

# ToC
toc:
  min_level: 2
  max_level: 3